"""take 2

Revision ID: 76bc4f366b45
Revises: 5f5c9f85d0ad
Create Date: 2021-05-03 23:07:11.058685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bc4f366b45'
down_revision = '5f5c9f85d0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'user_id_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friends', 'user_id_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('friends_user_id_1_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_user_id_2_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['user_id_1'], ['id'])
    op.create_foreign_key(None, 'friends', 'users', ['user_id_2'], ['id'])
    op.drop_column('friends', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user_id_2_fkey', 'friends', 'users', ['user_id_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('friends_user_id_1_fkey', 'friends', 'users', ['user_id_1'], ['id'], ondelete='CASCADE')
    op.alter_column('friends', 'user_id_2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friends', 'user_id_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
