"""take 15

Revision ID: 6cb3f12677dd
Revises: 635d8acfe767
Create Date: 2021-05-04 17:24:58.176317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb3f12677dd'
down_revision = '635d8acfe767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipients_private_message_id_fkey', 'recipients', type_='foreignkey')
    op.drop_column('recipients', 'private_message_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('private_message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('recipients_private_message_id_fkey', 'recipients', 'private_messages', ['private_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
