"""take 18

Revision ID: 0a41f89d599f
Revises: 94b5a434302e
Create Date: 2021-05-06 12:28:45.049307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a41f89d599f'
down_revision = '94b5a434302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipients', 'private_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('recipients_private_message_id_fkey', 'recipients', type_='foreignkey')
    op.create_foreign_key(None, 'recipients', 'private_messages', ['private_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipients', type_='foreignkey')
    op.create_foreign_key('recipients_private_message_id_fkey', 'recipients', 'private_messages', ['private_message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recipients', 'private_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
