"""take 17

Revision ID: 94b5a434302e
Revises: aaf59e1d6463
Create Date: 2021-05-04 17:34:15.796456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b5a434302e'
down_revision = 'aaf59e1d6463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('private_messages_recipient_id_fkey', 'private_messages', type_='foreignkey')
    op.drop_column('private_messages', 'recipient_id')
    op.add_column('recipients', sa.Column('private_message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipients', 'private_messages', ['private_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipients', type_='foreignkey')
    op.drop_column('recipients', 'private_message_id')
    op.add_column('private_messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('private_messages_recipient_id_fkey', 'private_messages', 'recipients', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
